### PR TITLE
Update falcon4_os1 gains for Gazebo simulation

### PR DESCRIPTION
**Pull request by XuRobotics**

### CODE REVIEW

**Comment by tdinesh** [comment]
While you are at it, can you also test/update gains for the non-os1 model?

**Comment by tdinesh** [comment]
Yes, that't the general practice. All the tmux scripts are under `quadrotor_control/kr_mav_launch/scripts`. Currently, its not open sourced, so keeping instructions to individual launch lines.

**Comment by ljarin** [comment]
okay forgot they were there. Maybe you could put a temporary note or something that the control launch file therefore won't work without quadrotor_control?

We're providing code that is already tested such that you don't need to debug it, but I accept this as personal preference.

**Comment by tdinesh** [comment]
That is a good point!

**Pull request merged**
